version: '3.8'

services:
  db:     # TODO: Research other configurations [command, healthcheck, restart, tty, stdin_open]
    image: postgres:14
    container_name: modera_postgres_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pg_data
    ports:
      - "5434:5432"
    volumes:
#      - postgres_data:/var/lib/postgresql/data/pg_data
      - ./.dockers/pg_data:/var/lib/postgresql/data/pg_data


volumes:
  postgres_data: